#!/bin/bash

ALL_ADDRESSES=$(mktemp "all-XXXXX") || exit 1

cat addresses-* | sort | uniq >> ${ALL_ADDRESSES}

comm -2 -3 x ${ALL_ADDRESSES} > x01

rm ${ALL_ADDRESSES}

exit

#comm -2 -3 x addresses-3.0 > x01
#comm -2 -3 x01 addresses-3.1 > x02
#comm -2 -3 x02 addresses-3.2 > x03
#comm -2 -3 x03 addresses-3.3 > x04
#comm -2 -3 x04 addresses-3.4 > x05
#comm -2 -3 x05 addresses-3.5 > x06
# and so on...
