#!/bin/sh
kernel_version="6.1"
addrfile="addresses-${kernel_version}"
subject="Linux kernel development reports for the ${kernel_version} release"
msg="email_message"

if [ ! -f "$addrfile" ] ; then
	echo "Error: $addrfile file not found"
	exit 1
fi

if [ ! -f "$msg" ] ; then
	echo "Error: $msg file not found"
	exit 1
fi

while read -r address
do
	echo "sending message for ${kernel_version} to $address"
	mutt -s "$subject" "$address" <  $msg >> spam.log 2>&1
	

	if [ $? -ne 0 ]; then
        echo "Error: failed to send email to $address"
        fi

	
#	sleep 1
done < "$addrfile"

