#!/bin/sh
addrfile="addresses-4.20"
subject="Linux kernel development reports for the 4.20 release"
msg="email_message"

for address in `cat $addrfile`
do
	echo "sending to $address"
	mutt -s "$subject" "$address" <  $msg >> spam.log 2>&1
#	sleep 1
done

